DigitalSlideArchive/ImageDePHI

- README.md
- imagedephi.py
- requirements.txt
This PR creates an initial CLI tool to lay out some framework for Image DePHI. 
Given a directory of images and a directory to write output to, the tool uses `tifftools` to open each image, traverse the `ifds` and replace the value of the `ImageDescription` tag (270) with `"Redacted by Image DePHI"`. The modified `ifds` are written as a new tiff in the specified output directory with the filename `REDACTED_<original file name>`.
> Create initial redaction CLI

- imagedephi.py
- mypy.ini
- pyproject.toml
- requirements.txt
- tox.ini
This PR adds some testing for Image DePHI, which can be built upon to accommodate more kinds of testing.
We are using `tox` to configure tests. For now, linting, import sorting, type checking, and formatting have been added.
> Add initial tox/black/mypy config

- .git-blame-ignore-revs
- imagedephi.py
- pyproject.toml
- setup.py
- stubs/tifftools/__init__.pyi
- stubs/tifftools/constants.pyi
- stubs/tifftools/tifftools.pyi
- tox.ini
This has several benefits:
* String quotes are now auto-formatted correctly; no need to fix quote-related Flake8 errors by hand.
* Continue to type the quotes however you want. Black will just fix them afterwards.
* We can unpin Flake8.
Note the addition of `.git-blame-ignore-revs`, to avoid `git blame` attribution of these automated changes. See https://github.blog/changelog/2022-03-24-ignore-commits-in-the-blame-view-beta/ and [run `git config --global blame.ignoreRevsFile .git-blame-ignore-revs` locally if you want automatic support](https://michaelheap.com/git-ignore-rev/).
> Allow Black to handle string quote formatting

- pyproject.toml
This allows pip (and Tox via pip) to use modern build system hooks to communicate with setuptools, instead of the legacy pathway.
> Add PEP 517 build information

- tox.ini
This makes `tox` significantly faster to run.
> Upgrade to Tox 4 and use editable installs

- pyproject.toml
- setup.py
This provides stronger validation (since the information is static, not dynamically computed by executing `setup.py`). It is also the preferred format for `setuptools-scm`, which will help with dynamic versioning in the future.
Fixes #21.
> Use PEP 621 for setuptools metadata

- imagedephi/__init__.py
At runtime (when `TYPE_CHECKING` is False), some of the annotation symbols are not actually defined.
> Enable postponed evaluation of annotations

- tests/data/input/test_image.tif
- tests/test_redact_images.py
- tox.ini
Resolves #4 
Now our testing suite contains a new environment called `test`, which will run `pytest` tests for Image DePHI. There is now a single test that tests the `redact_images` method, as well as some test data (a blank tiff image created by `large_image_converter`).
> Create initial functional tests

- imagedephi/gui.py
- imagedephi/templates/DirectorySelector.html.j2
- tests/test_gui.py
Allows a user to traverse two directory trees independently and select an input and output directory for images:
> Output directory selector

- imagedephi/gui.py
Our CI started failing because Black cut a new release, which our code did not adhere to. 
Specifically, [this change](https://github.com/psf/black/pull/3035)
Now our code conforms to this new rule.
> Reformat with black v23

- imagedephi/gui.py
- imagedephi/main.py
- imagedephi/redact.py
Fixes #48 
A new flag has been added to the `run` command to allow overwriting existing output in the output directory.
Ex: `imagedephi run images/ output/ -o`
**Previous Behavior**
The `run` command would fail silently when attempting to write to an existing file.
**New Behavior**
Running `imagedephi run` without the new flag will not write over existing output images. For each image it cannot save due to existing files, it will print a message for the user informing them of what is happening.
Running `imagedephi run` with the new flag will overwrite existing redacted images, and also report to the user that it is doing so.
> Handle case where previous output exists

- MANIFEST.in
This is causing error messages when building an sdist, and causing package data to not be bundled on Windows.
Fixes #69.
> Don't use trailing slashes in MANIFEST.in

- imagedephi/main.py
- imagedephi/utils/cli.py
- imagedephi/utils/os.py
- tests/conftest.py
- tests/test_e2e.py
- tests/test_utils_cli.py
- tests/test_utils_os.py
On Windows, this will cause the ImageDePHI GUI to start when a user runs `imagedephi.exe` directly from Windows Explorer. In all other cases (non-Windows and Windows CLI usage), the existing behavior (running with no arguments prints help text) is unchanged.
This is implemented via a new `FallthroughGroup` subclass of `click.Group`. This implementation abstracts the logic of falling through out of the main CLI endpoints (which are more concerned with handling arguments). The decoupled `FallthroughGroup` is also easier to test.
A new `launched_from_windows_explorer` utility uses Windows platform APIs to determine whether the current ImageDePHI process is running via a Windows command line shell or was launched directly by Windows Explorer. See code comments for implementation details.
> Launch the GUI when run directly from Windows Explorer

- .github/workflows/ci.yml
- MANIFEST.in
- imagedephi/main.py
- pyproject.toml
- tests/test_e2e.py
This adds a `--version` CLI option and an associated end-to-end test.
To support that option and future release workflows, it uses [setuptools-scm](https://pypi.org/project/setuptools-scm/) to set the version as distribution metadata.
setuptools-scm will look at the Git history, find the nearest tag, and dynamically compute a version number. Note, `setuptools-scm` also attempts to add all tracked Git files into the source distribution ("sdist"), so rigorous exclusions in `MANIFEST.in` are necessary to avoid bloat.
> Add a "--version" option and internal support for git-based versioning

- imagedephi/templates/BaseSelectorWidget.html.j2
- imagedephi/templates/InputSelectorWidget.html.j2
- imagedephi/templates/OutputSelectorWidget.html.j2
In the template context `request.url` returns [a `URL` object](https://www.starlette.io/requests/#url), which contains all the query parameters of the current endpoint. By calling `URL.include_query_params`, it's possible to selectively overwrite only the query parameters which need to change. This also has the advantage of internally handling URL encoding, so we don't have to manually assemble a query string.
> Simplify template URL creation

- .github/workflows/ci.yml
Seeing whether a failure is exclusive to one platform is useful.
> Do not cancel all CI runs when one fails

- imagedephi/gui.py
- tests/test_e2e.py
This should resolve some of the test crashes seen on Windows.
> Shut down the GUI server on internal errors

- tests/test_gui.py
This will make the tests more resilient to updating URLs.
Also fix some GUI test names.
> Use endpoint names instead of URL paths in tests

- imagedephi/gui.py
- imagedephi/main.py
This will cause the CLI to exit with a non-zero status code on errors.
> Propagate HTTP endpoint exceptions to the CLI

- imagedephi/redact/build_redaction_plan.py
- imagedephi/redact/svs.py
- imagedephi/redact/tiff.py
Redaction classes will handle both metadata and image redaction (#102), so the names `TiffMetadataRedactionPlan` and `SvsMetadataRedactionPlan` were not appropriate.
> Rename redaction classes

- .gitignore
Adding to gitignore so we don't accidentally commit images redacted while testing.
> Don't commit Redacted images

- imagedephi/base_rules.yaml
Fix #114 
Cover SVS image description metadata that can be generated by Leica G450 scanners.
> Cover additional image description keys

- imagedephi/redact/redact.py
- imagedephi/redact/tiff.py
Fixes #117 
These images can technically be opened by `tifftools`, but can't be written back out as those formats post redaction. Therefore, we should skip redaction on these kinds of images, instead of trying to redact and reporting as a failed redaction.
> Don't attempt to redact ImageJ, NDPI files

- .gitignore
- imagedephi/base_rules.yaml
- imagedephi/redact/redact.py
- imagedephi/rules.py
- tests/override_rule_sets/example_user_rules.yml
- tests/test_e2e.py
- tests/test_redact.py
This PR updates how we name redacted files. Instead of prepending `REDACTED_` to the input file names, prefix defined in the rules and a number, which increments with each slide redacted so far in the current run of Image DePHI.
It introduces a new property for `RuleSet`s: `output_file_name`. If `output_file_name` is `redacted_image`, then redacted images will follow the naming pattern `redacted_image_1.svs`, `redacted_image_2.svs`, etc.
This makes it harder to map back to the original file without comparing the images in the output and input directories. Future improvements could be including the SHA of the original image in the redacted image metadata.
Fix #60
> Use better name for redacted images

- imagedephi/redact/tiff.py
Fix #133 
Fixes a bug in `_iter_ifds` that would cause an IFD to be `yield`ed once for each non-IFD tag contained within.
> Fix bug in iter_ifds returning IFDs several times

- imagedephi/redact/svs.py
- imagedephi/redact/tiff.py
This PR changed how redaction plans are reported. Now, we display all of the redaction steps per IFD, instead of per tag/key.
This means that if multiple IFDs in an image have an `ImageDescription`, the report will break down what the redaction will look like for all instances of `ImageDescription`.
This is important because now we loop through the IFDs and tags of images when displaying the report. Because of this change, we have access to the metadata while printing the plan. In the future, this will make it easier to actually include the changes that will be made in the report, or display them in the UI.
It will also help future development for rules that sometimes delete metadata and sometimes keep metadata (e.g. type-checking rules).
> Revamp redaction report

- imagedephi/redact/svs.py
- imagedephi/redact/tiff.py
- imagedephi/rules.py
- tests/override_rule_sets/example_user_rules.yml
- tests/test_redact.py
This PR introduces a first pass at a new metadata rule type: `check_type`. 
Redaction for these kinds of rules will check the datatype of metadata on the image and either:
1. Remove the metadata if the datatype of existing data doesn't match what the rule states the datatype should be
2. Keep the metadata if it is of the expected type
As a first pass, these rules are tailored for tiff metadata. They have an `expected_type` and `expected_count` property, which are analogs to `tifftools.Tag`'s `datatype` and `count`.
> Add rule type for datatype checking

- README.md
Add documentation to explain how ImageDePHI rules are formatted and how they are used during runs of the program.
Reviewers: please leave feedback regarding how the new documentation can be made more clear, and/or additional information that would be useful for end users.
> Document rules format

- .gitignore
- imagedephi/redact/svs.py
- stubs/tifftools/constants.pyi
- tests/test_redact.py
Fix #142 
Some SVS files have IFDs that represent an associated image but do NOT have the `ImageDescription` tag.
Previously, redaction for svs images assumed the existence of `ImageDescription` for every IFD in the image.
Now, if the `ImageDescription` is not found, or if the type of associated image could not be determined from the `ImageDescription` tag, we fall back to tag 254, `NewSubfileType`. This is a bitmask, and we can determine if an IFD represents a macro image from this bitmask.
A test has also been added, but this test uses a hard-coded IFD-like dictionary instead of a new image. It didn't feel worth it to add a new image to LFS to test this particular case, but I'm open to revisiting this decision if the added test is not sufficient.
> Determine associated image type without ImageDescription

- imagedephi/gui.py
- pyproject.toml
Fix #151 
This PR adds a fallback method to obtain a thumbnail image from a tiff/svs file when PIL can't open a thumbnail IFD. This is necessary because PIL's tiff reader can't read tiff images that are JPEG2k encoded.
In this case, the low res image determined to be the thumbail is extracted from the original tiff/svs image data.
To see the endpoint in action, run `imagedephi gui` and point your browser towards: 
`localhost:<port>/image/?file_name=<path/to/file>&image_key=thumbnail`
> Extract thumbnail image data when PIL can't read an IFD

- imagedephi/gui.py
- imagedephi/utils/logger.py
Some change in the last few weeks to fastapi has caused CI to start throwing errors.  Specifically fastapi<0.107 works, but 0.107 requires that the Jinja template directory parameter not be an empty string.
> Harden Jinja expectations and logger errors

- imagedephi/gui.py
- imagedephi/main.py
- imagedephi/redact/redact.py
- imagedephi/utils/logger.py
- tests/test_e2e.py
Fix #171 
Add an option to the `run` command to keep original file names, in the case where users are confident that their image file names do not contain PHI but would be helpful to preserve after redaction.
To use: 
`imagedephi run path/to/images -o output/path --skip-rename`
> Add flag to skip renaming files

- imagedephi/main.py
- imagedephi/redact/redact.py
- tests/test_e2e.py
Fix #170 
Adds a new flag (`-r` or `--recursive`).
If this flag is provided to the `imagedephi run` command, then redaction will be performed on sub directories of the input directory. Additionally, the directory structure will be duplicated in the output directory.
> Allow redacting on subdirs

- imagedephi/base_rules.yaml
- imagedephi/redact/build_redaction_plan.py
- imagedephi/redact/dicom.py
- imagedephi/redact/redact.py
- pyproject.toml
- tests/data/input/dcm/test_dcm_image.dcm
- tests/test_redact.py
Here is the initial set of changes to support redacting DICOM images.
As a start, only metadata redaction is supported and only redaction of single .dcm files is supported.
(TODO before ready for full review/merge):
> Implement DICOM metadata redaction

- .github/workflows/ci.yml
- README.md
- tox.ini
Otherwise, the binary fails because it can read some modules it expects to be present.
> Include dicom encoders in the binary

- tox.ini
`type` tests were failing, claiming falsely that `Image.LANCZOS` did not exist.
> Add types-Pillow to tox type test

- client/.eslintrc.cjs
- client/package.json
- client/src/HomePage.vue
- client/yarn.lock
A combination of out-of-date packages and incorrect config caused linting to break
- Updates eslint and dependencies
- Adds vue-elsint-parser 9.*  which is required for <script setup>
> Update packages and config for UI linting

- .github/workflows/ci.yml
Pins workflow runner to macos14  to address connectivity issues found in macos12.
> Explicitly use macos14

- imagedephi/redact/redact.py
- pyproject.toml
The [tqdm](https://tqdm.github.io/) progress bar supports [redirection of logging](https://tqdm.github.io/docs/contrib.logging/#logging_redirect_tqdm) in order to keep the progress bar in place while other application output is printed for the user. This is especially helpful for running the CLI with the verbose (`-v`) flag.
Fix #216
> Use tqdm for progress bar

- imagedephi/redact/svs.py
@marySalvi from the discussion today it was clear that this variable name was unclear. I think changing it from `match_counts` -> `associated_image_count_by_rule` makes a big difference. Let me know if you have a different suggestion.
> Rename `match_counts` to be more clear

- imagedephi/redact/redact.py
- tests/test_e2e.py
- tests/test_redact.py
Fix #220 
Create a file that is the sibling of the redacted directory. The file is a csv and contains a mapping of input file names to output file names.
This change replaces the `create_redact_dir` function with `create_redact_dir_and_manifest`, which functions nearly identically except it also creates (via `<path>.touch()`) the manifest file and returns a 2-value tuple `(output_dir, manifest_path)` where both values are paths. The test written for `create_redact_dir` has been updated to reflect this change.
TODO:
> Write a csv summary of redaction runs

- imagedephi/gui/api/api.py
- imagedephi/gui/utils/image.py
Builds off of the max image pixels for Image DePHI introduced by #224.
Before attempting to read the IFD image data for the lowest res IFD, check its size. If the total number of pixels is > 1,000,000,000, throw an exception, and handle the exception appropriately in calling code.
> Apply image size checks consistently

- imagedephi/minimum_rules.yaml
In dicom it is PhotometricInterpretation.  We used the wrong one in the minimum rule set.
> The name of the photometric tag in tiff is photometric

- imagedephi/redact/redact.py
Depending on the exception, the error logging itself could fail.
> Harden error logging

- client/src/HomePage.vue
- imagedephi/gui/api/api.py
Fixes #251 
Modelling after vite's [websocket](https://github.com/vitejs/vite/blob/587ad7b17beba50279eaf46b06c5bf5559c4f36e/packages/vite/src/client/client.ts#L175-L187) architecture, this implements a very simplified version:
- Periodically 'pinging' server
- Removes the server side 'heartbeat' 
- Reduces messaging delay (This is the most simplified portion since vite's HMR looks for changes in modules)
> Ping from frontend and reduce delay in messaging

- README.md
- imagedephi/minimum_rules.yaml
- imagedephi/redact/build_redaction_plan.py
- imagedephi/redact/redact.py
- imagedephi/rules.py
- tests/test_redact.py
Previously, "strict" redaction was done only by specifying a redaction profile from the command line. Now, rule sets themselves can be flagged as `strict`.
Effectively, this means that there is now no difference between running 
`imagedephi --profile strict ...` 
and 
`imagedephi -R minimum_rules.yaml ...`
Users can now create their own "strict" rule sets using this flag, and all tags not specified by that rule set would be deleted.
Documentation has been updated and a new test has been added.
> Add `strict` to rule sets

- client/src/HomePage.vue
- client/src/api/rest.ts
- client/src/components/FileBrowser.vue
- client/src/components/ImageDataDisplay.vue
- client/src/components/ImageDataTable.vue
- client/src/components/MenuSteps.vue
- client/src/store/imageStore.ts
- client/src/store/redactionStore.ts
- client/src/store/types.ts
- imagedephi/redact/redact.py
This PR contains several smaller UI/UX improvements:
- Fixes sporadic white lines in the ImageData table header
- ImageData table remains visible during redaction
- Alters hover color on 'DE-PHI' button to not look disabled
- Resets progress counter to 0 on new redaction
- Redaction snackbar closes for new workflow (both new redaction and new input directory selection)
- Resets tags when new input directory is selected
> Redaction ux improvements

- imagedephi/gui/api/api.py
- imagedephi/main.py
- imagedephi/redact/redact.py
- tests/test_e2e.py
- tests/test_redact.py
Fixes #261 
Fixes #262 
- Changes Override_rules to be a global option
- Changes Override_rules type to Path and validates the ruleset later on
- Checks the parent param for every global option so as not to overwrite it
> Harden global options

- client/src/HomePage.vue
- client/src/store/types.ts
- imagedephi/main.py
- imagedephi/redact/redact.py
- imagedephi/redact/redaction_plan.py
- imagedephi/redact/svs.py
- tests/test_redact.py
Closes #236 
Closes #237 
**Backend Changes**
- Created a failed directory and failed manifest file at start of redaction
- Each failed image is copied to the failed directory and logged to the manifest
- At the end of the redaction the command needed to re-redact the failed images is logged to the manifest
- Adds an index option to `run` command that indicates the starting number for renaming during redaction
- Originally if an image was skipped, the image counter would increase and thus, that number would be skipped in naming. => Now there is an additional counter that increases on successes.
**Frontend Changes**
- Adds a confirmation Modal when an image set has images with missing rules 
- Continue forces redaction as described above
- Cancel closes the modal and allows the user to add …
> Handle missing rules

- imagedephi/utils/cli.py
- tests/test_e2e.py
Fix #70 
Modify the `invoke` method of `FallthroughGroup` by handling the case where a provided subcommand does not match a subcommand actually offered by the `FallthroughGroup`.
> Show help text for unknown subcommands

- imagedephi/redact/build_redaction_plan.py
- tests/conftest.py
- tests/test_redact.py
Fix #210 
Removes the FILE_EXTENSION_MAP in favor of an existing utility function to determine if an image with TIFF magic numbers is an Aperio file.
A new test image and test have been added as well. The test makes sure the correct redaction plan `__init__` function gets called for an svs file with no extension.
> Remove reliance on file extension to get format

- client/src/HomePage.vue
- client/src/components/FileBrowser.vue
- client/src/components/ImageDataTable.vue
- client/src/components/InfiniteScroller.vue
- Adds a loading feedback on the filebrowser
- Makes the Image Data Table 'denser', expand across more of the page and increases image preview size (slightly)
- Image lists for the filebrowser are created dynamically based on the space available.
> UI improvements

- pyproject.toml
- tests/test_redact.py
Looks like there's a difference in representation of tags in (gggg, eeee) form between pydicom 2.X and 3.0. This caused a test to fail for us. 
If using (gggg,eeee) form in rules, they must not have a space after the comma.
> Unpin dependencies and fix test rule definition

- client/src/HomePage.vue
- client/src/components/FileBrowser.vue
- client/src/components/MenuSteps.vue
- client/src/store/directoryStore.ts
- client/src/store/imageStore.ts
- imagedephi/gui/api/api.py
- tests/test_gui.py
Saves the selected directories on update to localStorage and retrieves as the loading default.
> Store selected directories in localStorage

- docs/demo.md
- imagedephi/command_file.py
- imagedephi/gui/api/api.py
- imagedephi/gui/utils/directory.py
- imagedephi/main.py
- imagedephi/redact/__init__.py
- imagedephi/redact/redact.py
- tests/conftest.py
- tests/test_redact.py
Closes #288 
Closes #101
- Updates `input_path` for variadic option input
- Adds ability for a user to pass a file with command details to `run` and `plan`
- Updates the demo to include this feature
> 288 yaml dephi input
