imagedephi/__main__.py, imagedephi/gui.py, imagedephi/main.py, imagedephi/redact.py, tests/conftest.py, tests/test_e2e.py
=> Clean up file structure and imports

imagedephi/gui.py, tests/test_e2e.py
Adds image redaction functionality to the gui.
=> Gui redaction

imagedephi/gui.py, imagedephi/redact.py, imagedephi/templates/BaseSelectorWidget.html.j2, imagedephi/templates/DirectorySelector.html.j2, imagedephi/templates/InputSelectorWidget.html.j2, imagedephi/templates/OutputSelectorWidget.html.j2, pyproject.toml, tests/test_e2e.py, tests/test_gui.py, tox.ini
Displays supported images(svs and tif) in directory list.
=> Gui display files

imagedephi/redact.py
=> Use standard FILE_EXTENSION_MAP

.github/workflows/ci.yml, MANIFEST.in, imagedephi/gui.py, pyproject.toml, tox.ini
=> Add support for building the application as a single binary

.github/workflows/ci.yml
=> Run CI on an older Linux

imagedephi/main.py, imagedephi/utils/network.py, tests/test_utils_network.py
=> Use a random port for serving the GUI

.github/workflows/ci.yml, imagedephi/main.py, imagedephi/rules/rule.py, pyproject.toml, stubs/tifftools/tifftools.pyi, tox.ini
=> Upgrade to Python 3.11

imagedephi/gui.py
See: https://fastapi.tiangolo.com/advanced/events/
=> Switch to FastAPI's preferred new syntax for lifespan

README.md
=> Add additional mac instructions

pyproject.toml
Fix #136 
It seems like the click issue linked in #136 has some momentum, so  I'm going ahead and pinning `click` for now.
=> Pin click while tests fail

imagedephi/gui.py, imagedephi/redact/redact.py, imagedephi/redact/tiff.py, pyproject.toml, tests/test_gui.py
Reports the redaction plan on run to show any images that will not be redacted and why.
=> Handle run failure

.github/dependabot.yml
This should make dependabot issues PRs to resolve #196.
=> Ask dependabot to make PRs to update github actions

README.md
Fix #119 
Clarify in the documentation which Ubuntu versions are supported.
=> Document linux version support clearly

README.md
=> Document DICOM support in README

imagedephi/minimum_rules.yaml
Fix #243 
This issue was brought up in #235
=> Add PlanarConfig to minimum rule set for tiff/svs

client/src/HomePage.vue, client/src/api/rest.ts, client/src/components/FileBrowser.vue, client/src/components/MenuSteps.vue, client/src/store/directoryStore.ts, client/src/store/imageStore.ts, client/src/store/types.ts, imagedephi/gui/api/api.py, imagedephi/gui/utils/directory.py
Closes #238 
Allows users to add and remove their own ruleset file and updates the redaction plan chart accordingly
=> UI rules feature

imagedephi/utils/image.py
There was a typo in the magic number list.
Fixes #266.
=> Fix detecting some tiff files

imagedephi/redact/dicom.py
Fix #259 
Its currently not necessary and causes the program to skip some files.
=> Remove WsiImageType enum

.github/workflows/ci.yaml, .github/workflows/release.yaml
=> Use correct node version and enable corepack
